### ISSUE TITLE
Q: how to define roles and user groups for Tenants?

### ISSUE THREAD

**Issue by matissg** [605data/strongbolt#32]
I just wanted to clarify if I understand Strongbolt functionality right:

1. `/strongbolt/roles` and `/strongbolt/user_groups` is for App`s Admin to define global roles/ user groups in App
2. by default Tenants cannot define roles and groups for their users, it has to be defined by the App`s Admin
3. if I need, I can adjust Strongbolt controllers, so Tenants can use `/strongbolt/user_groups` to add their users to particular user group

**Please, comment if I got it right?** In my App it is OK to have App's Admin, however I need to allow Tenants to have their Main User and some sub users. Then `require_ownership` and `require_tenant_access` would allow to have data protected for each of Tenants.

**Comment by tobithiel** [comment]
Yes, the Strongbolt default views are intended for an Admin. You can just write your own controllers which fill the tables `strongbolt_capabilities` and `strongbolt_capabilities_roles` if you need other users to manage permissions. Since Strongbolt's own controllers are internal it would be kind of awkward to alter their behavior from the outside, so doing your own controller is probably more straightforward.

`require_ownership` and `require_tenant_access` checks ownership of a record and access to a records tenant respectively.
You can just play around with 605data/strongbolt_example, which is already set up and working. It will allow you to test the difference between ownership and tenant access and see if that's what you are looking for.

**Comment by matissg** [comment]
Thank you. So if my Strongbolt `Tenant` would be `Compnay` with association like this:
```
class Company < ApplicationRecord
  has_many :accounts, dependent: :destroy
  has_many :users, through: :accounts
end

class User < ApplicationRecord
  has_many :companies, through: :accounts
  has_many :accounts, dependent: :destroy
end

class Account < ApplicationRecord
  belongs_to :user
  belongs_to :company
end
```
and I needed `User` to be able to define Roles and User Groups for its `Company`, I should create additional tables and appropriate associations something like this:

1. `capabilities_companies` with ` capability_id` and `company_id`
2. `roles_companies` with `role_id` and `company_id`

**Is my thinking correct, or you suggest different approach?** I'm new to coding and Rails so I'm asking probably silly questions :)

**Comment by tobithiel** [comment]
Your suggested approach won't work because Strongbolt will not look at your tables. You will need to create your own controller and check that the current_user is allowed to create/edit/delete the user groups and roles manually. Afterwards you save them to the tables Strongbolt provides and Strongbolt will pick them up and apply them.

**Comment by matissg** [comment]
I see, basically I don't create any new tables, however I allow `current_user` to:

1. create `user_groups` and `roles`
2. add to `user_groups` only users who have `current_user.companies`
3. link `roles` to `user_groups` where `current_user` is present

This should allow Tenants to see only their users, groups, roles. Probably I can propose some default Roles for any User, but if they want, then can add their custom Roles and group in their own group version. For example

- Role  "Main User" in App is general and can access all Models available for a Tenant, do anything, except Admin privileges.
- Role "Sales Person" can be general in App for any Tenant, however if some Tenant wants to restrict its "Sales Person", custom Role has to be created.

**Comment by tobithiel** [comment]
Sounds good 👍  I'm gonna close this, but feel free to reopen if the question isn't resolved yet.
